"""create repository ingestion tables

Revision ID: 754cc8b68188
Revises:
Create Date: 2026-07-20 21:31:58.703154

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "754cc8b68188"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("github_url", sa.String(length=500), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("github_id", name=op.f("uq_repositories_github_id")),
        sa.UniqueConstraint("github_url", name=op.f("uq_repositories_github_url")),
    )
    op.create_table(
        "repository_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(commit_sha) = 40", name=op.f("ck_repository_versions_commit_sha_length")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_versions_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_versions")),
        sa.UniqueConstraint(
            "repository_id", "commit_sha", name="uq_repository_versions_repository_commit"
        ),
    )
    op.create_index(
        op.f("ix_repository_versions_repository_id"),
        "repository_versions",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "queued", "running", "completed", "failed", name="ingestion_job_status"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_ingestion_jobs_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["repository_version_id"],
            ["repository_versions.id"],
            name=op.f("fk_ingestion_jobs_repository_version_id_repository_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_repository_version_id"),
        "ingestion_jobs",
        ["repository_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    op.drop_index(
        op.f("ix_ingestion_jobs_repository_version_id"),
        table_name="ingestion_jobs",
    )
    op.drop_table("ingestion_jobs")

    ingestion_job_status = sa.Enum(
        name="ingestion_job_status",
    )
    ingestion_job_status.drop(
        op.get_bind(),
        checkfirst=True,
    )

    op.drop_index(
        op.f("ix_repository_versions_repository_id"),
        table_name="repository_versions",
    )
    op.drop_table("repository_versions")
    op.drop_table("repositories")
