"""add ingestion tables and remove repository default branch

Revision ID: ea20bc7c066b
Revises: f4172fd60154
Create Date: 2026-07-19 04:51:09.397144

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea20bc7c066b"
down_revision: str | Sequence[str] | None = "f4172fd60154"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "default_branch")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "repositories",
        sa.Column(
            "default_branch",
            sa.VARCHAR(length=255),
            nullable=False,
            server_default="main",
        ),
    )

    op.alter_column(
        "repositories",
        "default_branch",
        server_default="main",
    )
    # ### end Alembic commands ###
