"""add ingestion jobs

Revision ID: f4172fd60154
Revises: 583f1c641847
Create Date: 2026-07-19 00:51:21.498088

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4172fd60154"
down_revision: str | Sequence[str] | None = "583f1c641847"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "queued", "running", "completed", "failed", name="ingestion_job_status"
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name="ck_ingestion_jobs_progress_range"
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["repository_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_repository_id"), "ingestion_jobs", ["repository_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_snapshot_id"), "ingestion_jobs", ["snapshot_id"], unique=False
    )
    op.create_index(op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_snapshot_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_repository_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")

    ingestion_job_status = sa.Enum(
        "pending", "queued", "running", "completed", "failed", name="ingestion_job_status"
    )
    ingestion_job_status.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
